export const Users=[
{
    id:1,
    profilePicture:'/assets/person/1.jpg',
    username:'safak',
},
{
    id:2,
    profilePicture:'/assets/person/2.jpg',
    username:'jan',
},
{
    id:3,
    profilePicture:'/assets/person/3.jpg',
    username:'sony',
},
{
    id:4,
    profilePicture:'/assets/person/9.jpeg',
    username:'rishi',
},
{
    id:5,
    profilePicture:'/assets/person/10.jpg',
    username:'kohlo',
},
{
    id:6,
    profilePicture:'/assets/person/11.png',
    username:'tim',
},
{
    id:7,
    profilePicture:'/assets/person/12.jpg',
    username:'pir',
},
];
export const Posts=[
    {
        id:1,
        desc:'love for all, hatre for none',
        photo:'/assets/person/13.jpg',
        date:'5 min ago',
        userId:1,
        like:32,
        Comment:9,
    },
    {
        id:2,
        photo:'/assets/person/14.jpg',
        date:'15 min ago',
        userId:2,
        like:30,
        Comment:10,
    },
    {
        id:3,
        photo:'/assets/person/15.jpg',
        date:'20 min ago',
        userId:3,
        like:2,
        Comment:1,
    },
    {
        id:4,
        desc:'life is beautiful',
        photo:'/assets/person/16.jpeg',
        date:'50 min ago',
        userId:4,
        like:40,
        Comment:10,
    },
    {
        id:5,
        desc:'life is  not sure',
        photo:'/assets/person/17.jpeg',
        date:'50 min ago',
        userId:5,
        like:40,
        Comment:10,
    },
    {
        id:6,
        desc:'life is beautiful',
        photo:'/assets/person/16.jpeg',
        date:'8 min ago',
        userId:6,
        like:40,
        Comment:10,
    },
    {
        id:7,
        desc:'life is beautiful',
        photo:'/assets/person/17.jpeg',
        date:'50 min ago',
        userId:7,
        like:47,
        Comment:10,
    },
    {
        id:8,
        desc:'life is beautiful',
        photo:'/assets/person/18.jpeg',
        date:'50 min ago',
        userId:8,
        like:40,
        Comment:10,
    },
]
   

